Add Gridlines to Kunduz
Theseus-Aegis/GTArmory pull request #43
Opened 2020-10-20 04:56 UTC by TyroneMF

- title.

Thanks @JoramD0

2020-10-20 05:02 UTC, JoramD0 requested changes

2020-10-20 10:34 UTC, jonpas reviewed
Should we put this into Mods as an optional?

So anyone can use it and we can easily remove it if we remove Kunduz in the future.

2020-10-20 10:43 UTC, JoramD0 commented
We could also try to give it to the person maintaining this version (if he/she is even still active).

2020-10-27 10:23 UTC, TyroneMF commented
Closed, PR to mods instead.
https://github.com/Theseus-Aegis/Mods/pull/463

2020-10-27 10:23 UTC, closed without merging